### ISSUE TITLE
Create userChrome.css article about it not being supported

### ISSUE THREAD

**Issue by rtanglao** [thundernest/knowledgebase-issues#13]
- [x] create article in SUMO KB ([draft in SUMO](https://support.mozilla.org/en-US/kb/userchromecss-js-usercontent-unsupported/history))
- [x] link to it from [Troubleshoot Mode Thunderbird](https://support.mozilla.org/kb/troubleshoot-mode-thunderbird) and any other relevant articles
- [x] Perhaps link to https://support.mozilla.org/en-US/kb/firefox-advanced-customization-and-configuration

**Comment by dannycolin** [comment]
FYI, https://support.mozilla.org/en-US/kb/firefox-advanced-customization-and-configuration#

**Comment by rtanglao** [comment]
> FYI, https://support.mozilla.org/en-US/kb/firefox-advanced-customization-and-configuration
excellent catch, not sure what do to here maybe link to it and ... ?

**Comment by dannycolin** [comment]
> excellent catch, not sure what do to here maybe link to it and ... ?

I think it'd be enough to mention that userChrome/Content also work in Thunderbird and link to this KB for instructions.

**Comment by rtanglao** [comment]
* For me in the future :-) :  `This also applies to Thunderbird. Please refer to Thunderbird's article: [[userChrome.css and .js and userContent are unsupported]]` to https://support.mozilla.org/en-US/kb/firefox-advanced-customization-and-configuration for future reference
