### ISSUE TITLE
NEW ARTICLE:  Thunderbird for Android version of : "Send usage data on Firefox mobile browsers"

### ISSUE THREAD

**Issue by rtanglao** [thundernest/knowledgebase-issues#178]
(following is from Google Doc: [Thunderbird for Android — Initial Release Planning](https://docs.google.com/document/d/1LfZFxPuM6O1AUFPPwtHnAX4qHkmvGHb25SLiH7aEWBo/edit))
* A Thunderbird for  Android version of the SUMO KB article: [Send usage data on Firefox mobile browsers](https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-browsers) 
* This article will be linked from the Google Play Store app listing
* Maybe note related information on how to delete the Firefox Account in the future when we have Sync (https://accounts.firefox.com/settings/delete_account) 
* This article will need approval by MZLA data steward @Sancus

**Comment by rtanglao** [comment]
* WIP: Google Doc: [Send Usage and technical data on Thunderbird for mobile devices](https://docs.google.com/document/d/1ZIqFBxumiyBdXHRjrnFXpBW5R4Dh5diZALTVmyHljQg/edit)

**Comment by wsmwk** [comment]
meeting with @kewisch  on Friday to discuss the draft https://docs.google.com/document/d/1qwWsiNQtX_348m3lscWHT0b2TwdUBrcv79yzOzAcQ18/edit?usp=sharing

**Comment by wsmwk** [comment]
@kewisch and I decided to base the android article instead on https://support.mozilla.org/en-US/kb/share-data-mozilla-help-improve-firefox

The first draft is at https://support.mozilla.org/en-US/kb/thunderbird-android-telemetry/revision/285717.  If you are unable to view that, please see https://docs.google.com/document/d/1mZXJ6Q2uvIer0m-O4qkEhay9wnfXqN5DPV-8PoElEHM/edit?usp=sharing

**Comment by kewisch** [comment]
@wsmwk This looks good to me. I made a few small suggestions in the doc, but we can also do them directly on SUMO. Do you want me to approve the SUMO page? (I still have access)

**Comment by wsmwk** [comment]
On 9/28/24 3:58 AM, Philipp Kewisch wrote:
> Do you want me to approve the SUMO page? (I still have access)

Thanks. No, I will apply your changes to SUMO when I make my next edit

**Comment by kewisch** [comment]
![data collection screenshot](https://github.com/user-attachments/assets/82b54d8d-b61c-4e15-a1b7-ab6fb53026eb)

Here is a screenshot for the data collection

**Comment by wsmwk** [comment]
Thanks.

@Sancus for your approval - updated article https://support.mozilla.org/en-US/kb/thunderbird-android-telemetry/revision/285803

**Comment by kewisch** [comment]
This is published now. Andrei - needing your approval was a misunderstanding. I will have our legal counsel look over this to ensure we're not contradictory to the privacy policy, and your names are somewhat similar.

Feel free to close this issue.

**Comment by wsmwk** [comment]
I marked ready for localization
