### ISSUE TITLE
Create TB115 version of Quick Filter Toolbar

### ISSUE THREAD

**Issue by rtanglao** [thundernest/knowledgebase-issues#6]
- [x] Modernize to 102 [Quick Filter Toolbar](https://support.mozilla.org/en-US/kb/quick-filter-toolbar) (hasn't been updated since 2017) and move 102 stuff to a new article.
<del>- [ ] Create a 115 version and replace the content in  [Quick Filter Toolbar](https://support.mozilla.org/en-US/kb/quick-filter-toolbar)  with the 115 content and link to the new 102 article</del>

**Comment by dannycolin** [comment]
@rtanglao I updated the information to match both 102 and 115. I didn't need to create a new page for 102 since a few `{for}` markups were enough to deal with the differences. 

Here's the link to the revision https://support.mozilla.org/en-US/kb/quick-filter-toolbar/revision/262560.

**Comment by rtanglao** [comment]
approved the revision, closing this issue, i assume `{for}` works :-) can reopen if it doesn't

**Comment by rtanglao** [comment]
* Filed [bug 1842096 Version picker: add Thunderbird 115 and leave 102 as default.](https://bugzilla.mozilla.org/show_bug.cgi?id=1842096 to request `tb115` be added to `showfor`
